SCHEMA = "ICWEBUSR"

create_users_table = '''create table ICWEBUSR.USERS (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CREATEDAT TIMESTAMP,
    CREATEDBY VARCHAR(255),
    EMAIL VARCHAR(255),
    ENABLED SMALLINT,
    FAILURES INTEGER,
    FIRSTNAME VARCHAR(255),
    LASTLOGIN TIMESTAMP,
    LASTNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    UPDATEDAT TIMESTAMP,
    UPDATEDBY VARCHAR(255),
    USERNAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
)'''

create_roles_table = '''create table ICWEBUSR.ROLES (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DESCRIPTION VARCHAR(255),
    ROLE_NAME VARCHAR(255),
    PRIORITY INTEGER,
    PRIMARY KEY (ID)
)'''

create_group_table = '''create table ICWEBUSR.GROUPS (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
)'''

create_user_role_table = '''create table ICWEBUSR.USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
)'''

create_user_group_table = '''create table ICWEBUSR.USER_GROUP (
    USER_ID BIGINT NOT NULL,
    GROUP_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, GROUP_ID)
)'''

create_group_role_table = '''create table ICWEBUSR.GROUP_ROLE (
    GROUP_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (GROUP_ID, ROLE_ID)
)'''

create_refresh_token_table = '''create table ICWEBUSR.RFSHTOKN (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CREATED_AT TIMESTAMP,
    EXPIRATION TIMESTAMP,
    ACCESS_TOKEN VARCHAR(1024),
    REFRESH_TOKEN VARCHAR(1024),
    REVOKED SMALLINT,
    USERNAME VARCHAR(255)
)'''

create_acl_class = '''create table ICWEBUSR.ACL_CLASS (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    CLASS VARCHAR(100) NOT NULL,
    CONSTRAINT ACL_CLASS_PKEY PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_UK_2 UNIQUE (CLASS)
)'''

create_acl_object_identity = '''create table ICWEBUSR.ACL_OBJECT_IDENTITY (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    OBJECT_ID_CLASS BIGINT NOT NULL,
    OBJECT_ID_IDENTITY VARCHAR(36) NOT NULL,
    PARENT_OBJECT BIGINT,
    OWNER_SID BIGINT,
    ENTRIES_INHERITING SMALLINT NOT NULL,
    CONSTRAINT ACL_OBJECT_IDENTITY_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_1 FOREIGN KEY (PARENT_OBJECT)
        REFERENCES ICWEBUSR.ACL_OBJECT_IDENTITY (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_2 FOREIGN KEY (OBJECT_ID_CLASS)
        REFERENCES ICWEBUSR.ACL_CLASS (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)'''

alter_aoi_one = '''CREATE UNIQUE INDEX UNIQUE_UK_3 ON 
ICWEBUSR.ACL_OBJECT_IDENTITY (OBJECT_ID_CLASS, OBJECT_ID_IDENTITY)'''

create_acl_sid = '''create table ICWEBUSR.ACL_SID (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY 
        (START WITH 1 INCREMENT BY 1),
    PRINCIPAL SMALLINT NOT NULL,
    SID VARCHAR(100) NOT NULL,
    CONSTRAINT ACL_SID_PKEY PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_UK_1 UNIQUE (SID, PRINCIPAL)
)'''

create_acl_entry = '''create table ICWEBUSR.ACL_ENTRY (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ACL_OBJECT_IDENTITY BIGINT NOT NULL,
    ACE_ORDER INTEGER NOT NULL,
    SID BIGINT NOT NULL,
    MASK INTEGER NOT NULL,
    GRANTING SMALLINT NOT NULL,
    AUDIT_SUCCESS SMALLINT NOT NULL,
    AUDIT_FAILURE SMALLINT NOT NULL,
    CONSTRAINT ACL_ENTRY_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_4 FOREIGN KEY (ACL_OBJECT_IDENTITY)
        REFERENCES ICWEBUSR.ACL_OBJECT_IDENTITY (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_5 FOREIGN KEY (SID)
        REFERENCES ICWEBUSR.ACL_SID (ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)'''
   
create_clusters = '''create table ICWEBUSR.icw_clusters (
    cluster_id VARCHAR(255) NOT NULL,
    alias VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT "icw_clusters_pk" PRIMARY KEY (cluster_id)
)'''

create_common_download = '''create table ICWEBUSR.icw_common_download (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY 
        (START WITH 1 INCREMENT BY 1),
    cluster_id VARCHAR(255),
    end_time TIMESTAMP,
    file_name VARCHAR(255),
    file_path VARCHAR(255),
    file_size BIGINT,
    message VARCHAR(255),
    percent_complete INTEGER,
    start_time TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    type VARCHAR(20) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    CONSTRAINT "icw_common_download_pk" PRIMARY KEY (id)
)'''

create_event_log_download = '''create table ICWEBUSR.icw_event_log_download (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY 
        (START WITH 1 INCREMENT BY 1),
    cluster_id VARCHAR(255),
    end_time TIMESTAMP,
    file_name VARCHAR(255),
    file_path VARCHAR(255),
    file_size BIGINT,
    message VARCHAR(255),
    percent_complete INTEGER,
    start_time TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    CONSTRAINT "icw_event_log_download_pk" PRIMARY KEY (id)
)'''

create_nodes = '''CREATE TABLE ICWEBUSR.ICW_NODES (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    cluster_id VARCHAR(255),
    nodeaddr VARCHAR(255),
    role SMALLINT NOT NULL DEFAULT 1,
    name VARCHAR(255),
    CONSTRAINT icw_nodes_pkey PRIMARY KEY (id)
)'''

create_report_record = '''create table ICWEBUSR.icw_report_record (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY 
        (START WITH 1 INCREMENT BY 1),
    api_job_name VARCHAR(50),
    api_message VARCHAR(255),
    api_node_name VARCHAR(50),
    api_response_code INTEGER,
    api_status_code INTEGER,
    api_user_name VARCHAR(50),
    cluster_id VARCHAR(5),
    created_date TIMESTAMP,
    download_status VARCHAR(20) NOT NULL,
    last_modified_date TIMESTAMP,
    message VARCHAR(255),
    pdf_path VARCHAR(100),
    percent_complete INTEGER,
    type VARCHAR(10),
    user_id VARCHAR(255),
    CONSTRAINT "icw_report_record_pk" PRIMARY KEY (id)
)'''

create_user_preference = '''create table ICWEBUSR.icw_user_preference (
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1 
        MINVALUE 1 MAXVALUE 2147483647 NO CACHE),
    key VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    value VARCHAR(255),
    CONSTRAINT "icw_user_preference_pk" PRIMARY KEY (id)
)'''


create_gateway_dbchangelog = f'''CREATE TABLE {SCHEMA}.GATEWAY_DBCHANGELOG (
	"ID" VARCHAR(255) NOT NULL,
	AUTHOR VARCHAR(255) NOT NULL,
	FILENAME VARCHAR(255) NOT NULL,
	DATEEXECUTED TIMESTAMP NOT NULL,
	ORDEREXECUTED INTEGER NOT NULL,
	EXECTYPE VARCHAR(10) NOT NULL,
	MD5SUM VARCHAR(35),
	DESCRIPTION VARCHAR(255),
	COMMENTS VARCHAR(255),
	TAG VARCHAR(255),
	LIQUIBASE VARCHAR(20),
	CONTEXTS VARCHAR(255),
	LABELS VARCHAR(255),
	DEPLOYMENT_ID VARCHAR(10)
)'''

create_gateway_dbchangeloglock = f'''CREATE TABLE  {SCHEMA}.GATEWAY_DBCHANGELOGLOCK (
	"ID" INTEGER NOT NULL,
	LOCKED SMALLINT NOT NULL,
	LOCKGRANTED TIMESTAMP,
	LOCKEDBY VARCHAR(255),
	PRIMARY KEY ("ID")
)'''

create_server_dbchangelog = f'''CREATE TABLE  {SCHEMA}.SERVER_DBCHANGELOG (
	"ID" VARCHAR(255) NOT NULL,
	AUTHOR VARCHAR(255) NOT NULL,
	FILENAME VARCHAR(255) NOT NULL,
	DATEEXECUTED TIMESTAMP NOT NULL,
	ORDEREXECUTED INTEGER NOT NULL,
	EXECTYPE VARCHAR(10) NOT NULL,
	MD5SUM VARCHAR(35),
	DESCRIPTION VARCHAR(255),
	COMMENTS VARCHAR(255),
	TAG VARCHAR(255),
	LIQUIBASE VARCHAR(20),
	CONTEXTS VARCHAR(255),
	LABELS VARCHAR(255),
	DEPLOYMENT_ID VARCHAR(10)
)'''

create_server_dbchangeloglock = f'''CREATE TABLE {SCHEMA}.SERVER_DBCHANGELOGLOCK (
	"ID" INTEGER NOT NULL,
	LOCKED SMALLINT NOT NULL,
	LOCKGRANTED TIMESTAMP,
	LOCKEDBY VARCHAR(255),
	PRIMARY KEY ("ID")
)'''

create_rptgeneration = f'''CREATE TABLE {SCHEMA}.RPTGENERATION (
    ID                  BIGINT GENERATED ALWAYS AS IDENTITY,
    IDENTIFIER          VARCHAR(100) NOT NULL,
    SCENARIO            VARCHAR(50) NOT NULL,
    CLUSTER_ID          VARCHAR(10) NOT NULL,
    MASTER_NODE         VARCHAR(50),
    OVERALL_STATUS      VARCHAR(30) NOT NULL,
    TOTAL_REPORTS       INTEGER,
    COMPLETED_REPORTS   INTEGER DEFAULT 0,
    FAILED_REPORTS      INTEGER DEFAULT 0,
    START_DATE          VARCHAR(8),
    START_TIME          VARCHAR(6),
    END_DATE            VARCHAR(8),
    END_TIME            VARCHAR(6),
    REQUEST_PARAMS      CLOB(1M) CCSID 1208,
    USER_ID             VARCHAR(100),
    MESSAGE             VARCHAR(500),
    CREATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PENDING_PHASE2       SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
)'''

create_rptgeneration_constraints = f'''ALTER TABLE {SCHEMA}.RPTGENERATION 
    ADD CONSTRAINT {SCHEMA}.RPTGEN_UQ1 
    UNIQUE (IDENTIFIER, CLUSTER_ID)'''

create_rptgeneration_indexes = f'''
CREATE INDEX {SCHEMA}.RPTGEN_IDX1 ON {SCHEMA}.RPTGENERATION (IDENTIFIER);
CREATE INDEX {SCHEMA}.RPTGEN_IDX2 ON {SCHEMA}.RPTGENERATION (CLUSTER_ID);
CREATE INDEX {SCHEMA}.RPTGEN_IDX3 ON {SCHEMA}.RPTGENERATION (OVERALL_STATUS);
CREATE INDEX {SCHEMA}.RPTGEN_IDX4 ON {SCHEMA}.RPTGENERATION (CREATED_AT);
CREATE INDEX {SCHEMA}.RPTGEN_IDX5 ON {SCHEMA}.RPTGENERATION (SCENARIO)
'''

create_rptjob = f'''CREATE TABLE {SCHEMA}.RPTJOB (
    ID                  BIGINT GENERATED ALWAYS AS IDENTITY,
    GENERATION_ID       BIGINT NOT NULL,
    REPORT_TYPE         VARCHAR(50) NOT NULL,
    COMMAND             VARCHAR(2000),
    JOB_ID              VARCHAR(100),
    JOB_NAME            VARCHAR(10),
    JOB_USER            VARCHAR(10),
    JOB_NUMBER          VARCHAR(6),
    JOB_STATUS          VARCHAR(20) NOT NULL,
    NODE_NAME           VARCHAR(50),
    START_TIME          TIMESTAMP,
    END_TIME            TIMESTAMP,
    ERROR_MESSAGE       VARCHAR(1000),
    SPOOL_FILE_COUNT    INTEGER,
    DATA_PERSISTED      SMALLINT DEFAULT 0,
    ROWS_PERSISTED      INTEGER,
    CREATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT {SCHEMA}.RPTJOB_FK1 
        FOREIGN KEY (GENERATION_ID) 
        REFERENCES {SCHEMA}.RPTGENERATION(ID)
        ON DELETE CASCADE
)'''

create_rptjob_indexes = f'''
CREATE INDEX {SCHEMA}.RPTJOB_IDX1 ON {SCHEMA}.RPTJOB (GENERATION_ID);
CREATE INDEX {SCHEMA}.RPTJOB_IDX2 ON {SCHEMA}.RPTJOB (JOB_ID);
CREATE INDEX {SCHEMA}.RPTJOB_IDX3 ON {SCHEMA}.RPTJOB (JOB_STATUS);
CREATE INDEX {SCHEMA}.RPTJOB_IDX4 ON {SCHEMA}.RPTJOB (REPORT_TYPE);
CREATE INDEX {SCHEMA}.RPTJOB_IDX5 ON {SCHEMA}.RPTJOB (DATA_PERSISTED)
'''

create_rptdata = f'''CREATE TABLE {SCHEMA}.RPTDATA (
    ID                  BIGINT GENERATED ALWAYS AS IDENTITY,
    GENERATION_ID       BIGINT,
    IDENTIFIER          VARCHAR(100) NOT NULL,
    REPORT_TYPE         VARCHAR(50) NOT NULL,
    JOB_ID              VARCHAR(100),
    ROW_COUNT           INTEGER DEFAULT 0,
    REPORT_DATA         CLOB(10M) CCSID 1208,
    CREATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (GENERATION_ID) REFERENCES {SCHEMA}.RPTGENERATION(ID)
)'''

create_rptdata_indexes = f'''
CREATE INDEX {SCHEMA}.RPTDATA_IDX1 ON {SCHEMA}.RPTDATA (IDENTIFIER);
CREATE INDEX {SCHEMA}.RPTDATA_IDX2 ON {SCHEMA}.RPTDATA (REPORT_TYPE);
CREATE INDEX {SCHEMA}.RPTDATA_IDX3 ON {SCHEMA}.RPTDATA (JOB_ID);
CREATE INDEX {SCHEMA}.RPTDATA_IDX4 ON {SCHEMA}.RPTDATA (IDENTIFIER, REPORT_TYPE);
CREATE INDEX {SCHEMA}.RPTDATA_IDX5 ON {SCHEMA}.RPTDATA (GENERATION_ID)
'''
create_rptanalysis = f'''CREATE TABLE ICWEBUSR.RPTANALYSIS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GENERATION_ID BIGINT NOT NULL,
    IDENTIFIER VARCHAR(100) NOT NULL UNIQUE,
    SCENARIO VARCHAR(50) NOT NULL,
    THRESHOLD_LEVEL VARCHAR(20) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    RESULT_DATA CLOB(256M),
    SUMMARY_DATA CLOB(256M),
    ERROR_MESSAGE VARCHAR(1000),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    PERCENT_COMPLETE INTEGER DEFAULT 0
)
'''
create_rptanalysis_indexes = f'''
CREATE UNIQUE INDEX ICWEBUSR.RPTANALYSIS_IDX1 ON ICWEBUSR.RPTANALYSIS (IDENTIFIER);
CREATE INDEX ICWEBUSR.RPTANALYSIS_IDX2 ON ICWEBUSR.RPTANALYSIS (GENERATION_ID)
'''

add_default_user_query = '''INSERT INTO ICWEBUSR.USERS (
    CREATEDAT, 
    CREATEDBY, 
    EMAIL, 
    ENABLED, 
    FAILURES, 
    FIRSTNAME, 
    LASTLOGIN, 
    LASTNAME, 
    PASSWORD, 
    UPDATEDAT, 
    UPDATEDBY, 
    USERNAME
) VALUES (
    CURRENT_TIMESTAMP, 
    'SYSTEM', 
    'admin@example.com', 
    1, 
    0, 
    'admin', 
    CURRENT_TIMESTAMP, 
    'admin', 
    '$2a$10$xWdh7eYXV2fB/a7EICIAgeh7EH0PUQlpMwGJGH5ysxy4ADN0vYxre', 
    CURRENT_TIMESTAMP, 
    'SYSTEM', 
    'admin'
)'''

add_role_p1 = '''INSERT INTO ICWEBUSR.ROLES (
    DESCRIPTION, 
    ROLE_NAME, 
    PRIORITY
) VALUES
    ('Admin Role', 'ROLE_ADMIN', 1),
    ('Superuser Role', 'ROLE_SUPERUSER', 2),
    ('User Role', 'ROLE_USER', 3)'''

add_user_role = '''INSERT INTO ICWEBUSR.USER_ROLE (
    USER_ID, 
    ROLE_ID
) VALUES (
    1, 
    1
)'''

add_group_g1 = '''INSERT INTO ICWEBUSR.GROUPS (
    NAME
) VALUES 
    ('Admins'),
    ('Superusers'),
    ('Users')
'''

add_group_role = '''INSERT INTO ICWEBUSR.GROUP_ROLE (
    GROUP_ID, 
    ROLE_ID
) VALUES 
    (1, 1),
    (2, 2),
    (3, 3)
'''

